// <auto-generated />
using System;
using HotelDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelDb.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelDb.Models.KeyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardNumber");

                    b.Property<int>("RoomId");

                    b.HasKey("Id");

                    b.ToTable("KeyCards");
                });

            modelBuilder.Entity("HotelDb.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BedCount");

                    b.Property<decimal?>("Cost")
                        .IsRequired();

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("RoomNickname");

                    b.Property<int>("RoomNumber");

                    b.Property<string>("RoomType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelDb.Models.RoomKeyCard", b =>
                {
                    b.Property<int>("RoomId");

                    b.Property<int>("KeyCardId");

                    b.HasKey("RoomId", "KeyCardId");

                    b.HasIndex("KeyCardId");

                    b.ToTable("RoomKeyCard");
                });

            modelBuilder.Entity("HotelDb.Models.RoomKeyCard", b =>
                {
                    b.HasOne("HotelDb.Models.KeyCard", "KeyCard")
                        .WithMany("RoomKeyCards")
                        .HasForeignKey("KeyCardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HotelDb.Models.Room", "Room")
                        .WithMany("RoomKeyCards")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
